version: "3"
services:
  livestream:
    image: ghcr.io/sb-im/sphinx:debug-amd64
    container_name: livestream
    command:
      - --debug
      - livestream
      - -c
      - /etc/sphinx/config.toml
    ports:
      - "5004:5004/udp"
      - "5005:5005/udp"
      - "1935:1935"
      - "127.0.0.1:6060:6060"
    volumes:
      - ../config/config.docker.toml:/etc/sphinx/config.toml:ro
    depends_on:
      - mosquitto
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ../config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: always
