version: "3"
services:
  livestream:
    image: ghcr.io/sb-im/sphinx:debug-amd64
    container_name: livestream
    command:
      - --debug
      - livestream
      - -c
      - /etc/sphinx/config.toml
    ports:
      - "5004:5004/udp"
      - "5005:5005/udp"
    volumes:
      - ../config/config.docker.toml:/etc/sphinx/config.toml:ro
      - /home/william/.ssh/id_ed25519.pub:/home/sphinx/.ssh/id_ed25519.pub:ro
    depends_on:
      - mosquitto
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ../config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: always
