version: "3.9"
services:
  livestream:
    image: ghcr.io/sb-im/sphinx:latest-dev-amd64
    container_name: livestream
    command:
      - --debug
      - livestream
      - -c
      - /config/config.yaml
    ports:
      - "5004:5004/udp"
    environment:
      - DEBUG_MQTT_CLIENT="${DEBUG_MQTT_CLIENT:-true}"
    volumes:
      - ../config/config.docker.yaml:/config/config.yaml:ro
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - mosquitto
    restart: on-failure

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ../config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: on-failure
