[machine_id]
uuid = "0cbab001-b037-4b0f-a687-d22a803eb363"

[mqtt]
clientID = "mqtt_edge"
username = "user"
password = "password"
server = "tcp://mosquitto:1883"

[mqtt_client]
topic_offer_prefix = "/edge/livestream/signal/offer"
topic_answer_prefix = "/edge/livestream/signal/answer"

# topic_candidate_send_prefix is opposite to cloud's topic_candidate_recv_prefix topic
topic_candidate_send_prefix = "/edge/livestream/signal/candidate/send"
# topic_candidate_recv_prefix is opposite to cloud's topic_candidate_send_prefix topic
topic_candidate_recv_prefix = "/edge/livestream/signal/candidate/recv"

topic_hook_stream_prefix = "/edge/livestream/hook"

qos = 2
retained = false

[webrtc]
ice_server = "stun:stun.l.google.com:19302"
ice_server_username = ""
ice_server_credential = ""

[drone_stream]
consume_stream_on_demand = false

protocol = "rtp"
host = "0.0.0.0"
port = 5004

[deport_stream]
consume_stream_on_demand = false

protocol = "rtsp"
addr = "rtsp://127.0.0.1:1234"

# rtp stream configuration for deport example
# protocol = "rtp"
# host = "0.0.0.0"
# port = 5005 # use a different port from drone stream source port

[hook_stream]
service = "sbcameradronemulti.service"
wait_timeout = "3s"
