# MQTT client config
mqtt-server: tcp://mosquitto:1883
mqtt-clientID: mqtt_edge
mqtt-username: user
mqtt-password: password

# MQTT client config for webRTC signaling
topic-offer: /edge/livestream/signal/offer
topic-answer-suffix: /edge/livestream/signal/answer
# topic-candidate-send-suffix is opposite to cloud's topic-candidate-recv-suffix topic
topic-candidate-send-suffix: /edge/livestream/signal/candidate/send
# topic-candidate-recv-suffix is opposite to cloud's topic-candidate-send-suffix topic
topic-candidate-recv-suffix: /edge/livestream/signal/candidate/recv
qos: 0
retained: false

# WebRTC config
ice-server: stun:stun.l.google.com:19302
ice-server-username: ""
ice-server-credential: ""

# RTP config
rtp-host: 0.0.0.0
rtp-port: 5004

# RTSP config
rtsp-addr: rtsp://127.0.0.1:1234
